Feat/pause contract
dopedao/prs pull request #3
Opened 2022-08-09 18:43 UTC by oscgu

2022-08-09 18:48 UTC, faces-of-eth requested changes
Couple of suggestions for tweaking this. I'd also think about suspending all withdraws when contract is paused in TaxableGame

2022-08-09 18:48 UTC, faces-of-eth commented on src/PRS.sol
> +    function contractState() public view onlyOwner returns (bool) {
I believe you don't need this and can access paused() directly without consequence. Would remove this.

2022-08-09 18:48 UTC, faces-of-eth commented on src/PRS.sol
> +    function pauseContract() public onlyOwner {
Maybe `pauseGame` or just `pause` ?

2022-08-09 18:48 UTC, faces-of-eth commented on src/PRS.sol
> +    function unpauseContract() public onlyOwner {
Same comment as above

2022-08-09 19:13 UTC, oscgu commented on src/PRS.sol
> +    function contractState() public view onlyOwner returns (bool) {
[cecbb6d](https://github.com/dopedao/prs/pull/3/commits/cecbb6ddf299bf18e9c278a462da8f9ca5c47c05)

2022-08-09 19:14 UTC, oscgu commented on src/PRS.sol
> +    function pauseContract() public onlyOwner {
[78016d3](https://github.com/dopedao/prs/pull/3/commits/78016d3228b27af4c362a3181bb383b944930daf)
[f617318](https://github.com/dopedao/prs/pull/3/commits/f617318b2cd4ace827bbce01b55c7d3da8330b3e)

2022-08-09 19:14 UTC, oscgu commented on src/PRS.sol
> +    function unpauseContract() public onlyOwner {
[78016d3](https://github.com/dopedao/prs/pull/3/commits/78016d3228b27af4c362a3181bb383b944930daf)
[f617318](https://github.com/dopedao/prs/pull/3/commits/f617318b2cd4ace827bbce01b55c7d3da8330b3e)

2022-08-10 01:52 UTC, faces-of-eth approved these changes
lgtm

2022-08-10 01:52 UTC, merged